name: Pull request
description: Report a bug you encountered
title: ""
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking time to contribute to the project!

        Please fill out the following text fields, so we get a clear understanding about your pull request.
        We will look at your pull request as soon, as we can.
  - type: textarea
    id: description
    attributes:
      label: What does your PR add / change?
      description: Tell us about the changes
      placeholder: Description ...
    validations:
      required: true
  - type: textarea
    id: motivation-and-context
    attributes:
      label: What is your motivation / context?
      description: Why is this change required? What problem does it solve?
      placeholder: Motivation & context ...
    validations:
      required: true
  - type: checkboxes
    id: written-tests
    attributes:
      label: Tests
      description: Have you written tests for your changes? 
      options:
        - label: Yes, I have
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/dv-oschl/test/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
