name: Bug Report
description: Report a bug you encountered
title: "Bug: "
labels: ["Type: Bug", "Priority: Medium", "Status: Pending"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Before reporting a bug, please look, if the bug was already reported.
        Please check the documentation, maybe you'll find a solution there.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us about the bug you encountered.
      placeholder: What? Where? When?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Tell us what behaviour you expected.
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the bug
      description: Give us step-by-step instructions how to reproduce the bug.
      placeholder: Step-by-step instructions
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version are you running?
      description: Please tell us the version or commit hash you are running.
      placeholder: Version number, docker image tag or commit hash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      placeholder: Paste the logs here
      render: shell
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: You can provide us additional information here (e. g. screenshots or videos)
      placeholder: More helpful information
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/dv-oschl/test/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
